package com.warroom.service.memory;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.UUID;

/**
 * Service to manage high-level conversation continuity and context formatting.
 * Serves as the memory bridge for AI agents during the debate process.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class ConversationMemoryService {

    private final RedisMemoryRepository memoryRepository;

    /**
     * Stores a new contribution from an AI agent into the session memory.
     * 
     * @param sessionId  the debate session ID
     * @param agentRole  the role of the agent (e.g., RESEARCHER, CRITIC)
     * @param jsonOutput the raw JSON string generated by the agent
     */
    public void addAgentMessage(UUID sessionId, String agentRole, String jsonOutput) {
        String formattedMessage = String.format("%s: %s", agentRole, jsonOutput);
        log.debug("Adding agent message to memory for session {}: role={}", sessionId, agentRole);
        memoryRepository.appendMessage(sessionId.toString(), formattedMessage);
    }

    /**
     * Consolidates the conversation history into a single string for LLM injection.
     * 
     * @param sessionId the debate session ID
     * @return a consolidated list of historical contributions or empty string
     */
    public String buildConversationContext(UUID sessionId) {
        List<String> messages = memoryRepository.getMessages(sessionId.toString());

        if (messages.isEmpty()) {
            return "";
        }

        log.debug("Building context from {} messages for session {}", messages.size(), sessionId);
        return String.join("\n\n", messages);
    }

    /**
     * Wipes session data when a debate is finalized or fails.
     * 
     * @param sessionId the debate session ID
     */
    public void clearSessionMemory(UUID sessionId) {
        log.info("Initiating cleanup of session memory for ID: {}", sessionId);
        memoryRepository.clearMemory(sessionId.toString());
    }
}
