package com.warroom.entity;

import com.google.cloud.spring.data.firestore.Document;
import com.google.cloud.firestore.annotation.DocumentId;
import lombok.*;

/**
 * Entity representing the specific improvement or critique generated by an AI
 * agent.
 */
@Document(collectionName = "agent_outputs")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AgentOutput {

    @DocumentId
    private String id;

    private String agentName;

    /**
     * The actual text output from the agent (Researcher, Critic, etc.)
     */
    private String output;

    private int iteration;

    private String generatedAt; // ISO-8601 string

    private String projectId; // Foreign key reference as String

    private String modelName; // e.g. "gemini-1.5-pro", "claude-3.5-sonnet"

    private String chatSessionId; // Foreign key reference as String
}
