server:
  port: 8080

spring:
  application:
     name: ai-research-war-room

  cloud:
    gcp:
      firestore:
        project-id: ai-war-room
        credentials:
          location: ${FIREBASE_CREDENTIALS:file:service-account.json}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:sk-or-v1-e9c...10b}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.7
          max-tokens: 3000

firebase:
  api-key: ${FIREBASE_API_KEY:AIzaSyBfxMGcCCOhpMXVMAft6ShnfR4gPjKzDUY}

logging:
  level:
    root: INFO
    com.warroom: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
